#USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/amazon/ariel/BoardConfigVendor.mk

LOCAL_PATH := device/amazon/ariel

# Board config
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_USE_UBOOT := true
TARGET_NO_RECOVERY := true
TARGET_BOARD_PLATFORM := mt8135
TARGET_NO_RADIOIMAGE := true
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_BOOTLOADER_BOARD_NAME := ariel
TARGET_RECOVERY_FSTAB := device/amazon/ariel/fstab.mt8135

#TARGET_GLOBAL_CFLAGS += -DAMAZON_LOG -DMTK_HARDWARE

mtk_flags := -DMTK_USEDPFRMWK

TARGET_GLOBAL_CFLAGS += $(mtk_flags)
TARGET_GLOBAL_CPPFLAGS += $(mtk_flags)
CLANG_TARGET_GLOBAL_CFLAGS += $(mtk_flags)
CLANG_TARGET_GLOBAL_CPPFLAGS += $(mtk_flags)

#2ND_TARGET_GLOBAL_CFLAGS += $(mtk_flags)
#2ND_TARGET_GLOBAL_CPPFLAGS += $(mtk_flags)
#2ND_CLANG_TARGET_GLOBAL_CFLAGS += $(mtk_flags)
#2ND_CLANG_TARGET_GLOBAL_CPPFLAGS += $(mtk_flags)

#~ BOARD_HAS_MTK_HARDWARE := true
MTK_DP_FRAMEWORK:=yes
#~ MTK_PATH_SOURCE := $(TOP)
#~ MTK_ROOT := $(TOP)
#~ MTK_PLATFORM := mt8135
#~ MTK_COMBO_SUPPORT := yes
#~ MTK_COMBO_CHIP := MT6628
#~ MTK_BT_SUPPORT := yes
#~ MTK_BWC_SUPPORT := yes
#~ MTK_WVDRM_SUPPORT := yes
#~ MTK_IN_HOUSE_TEE_SUPPORT := yes
#~ MTK_DRM_KEY_MNG_SUPPORT := yes
#~ MTK_DP_FRAMEWORK := yes
#~ MTK_DRM_APP := yes

# Sensors related
COMPILE_INVENSENSE_COMPASS_CAL :=1

# Wifi related
WPA_SUPPLICANT_VERSION :=VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER :=NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB :=lib_driver_cmd_mt66xx
BOARD_HOSTAPD_DRIVER :=NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_MODULE_PATH := /system/lib/modules/wlan_mt6628.ko
WIFI_DRIVER_MODULE_NAME := wlan_mt6628
WIFI_DRIVER_FW_PATH_PARAM:="/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA:=STA
WIFI_DRIVER_FW_PATH_AP:=AP
WIFI_DRIVER_FW_PATH_STA:=P2P

# Bluetooth related
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
#BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true

# Graphics related
USE_OPENGL_RENDERER := true

# kernel settings
#TARGET_NO_KERNEL := true
TARGET_PREBUILT_KERNEL :=$(LOCAL_PATH)/zImage-4.5.5
#TARGET_KERNEL_SOURCE := kernel/amazon/ariel-4.5.3
#TARGET_KERNEL_CONFIG:=mt8135_ariel_defconfig
BOARD_CUSTOM_BOOTIMG_MK :=$(LOCAL_PATH)/mkbootimg.mk
#BOARD_KERNEL_CMDLINE := console=ttyMT3,921600n1 vmalloc=496M slub_max_order=0
#BOARD_KERNEL_BASE := 0x10000000
#BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
#  - needs to be in base 10 for mk_ext4fs to work
BOARD_BOOTIMAGE_PARTITION_SIZE := 8388608
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 8388608
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1258291200
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1218838528
#BOARD_USERDATAIMAGE_PARTITION_SIZE := 5576834048
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5401018368
BOARD_FLASH_BLOCK_SIZE := 1024

# recovery-related settings
#BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_NO_REAL_SDCARD := true
